[user]
name = "Yannick Schini"
email = "yannick.schini@backmarket.com"

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()";

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"];

[ui]
editor = "nvim"
